# Generated by Django 5.2.dev20241120122318 on 2024-11-24 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(help_text='Capacity in number of items')),
                ('contact_details', models.CharField(max_length=255)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='markets.market')),
            ],
        ),
    ]
