# Generated by Django 5.2.dev20241120122318 on 2024-11-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('tracking_info', models.TextField(blank=True, null=True)),
                ('payment_details', models.CharField(max_length=255)),
            ],
        ),
    ]
